version: "3.8"

services:
  api:
    container_name: api
    build:
      context: api
      dockerfile: Dockerfile
    networks:
      - app-network
    ports:
      - 8080:8080
    restart: always
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    networks:
      - app-network
    ports:
      - 27018:27017
    volumes:
      - './mongo/mongod.conf:/etc/mongod.conf'
      - './mongo/create-user.sh:/docker-entrypoint-initdb.d/create-user.sh'
    env_file:
      - './mongo/.env'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    command: ["-f", "/etc/mongod.conf"]
networks:
  app-network:
    driver: bridge
